@startuml
start
:Предварительная обработка текста (очистка, lower case);
fork
  :Метод N-грамм;
  :Построить профиль документа (1-5 грамм);
  :Расчёт расстояния до профилей es/it;
  :Уверенность = 1 - (min / total);
fork again
  :Метод алфавитный;
  :Построить профиль (1-граммы);
  :Расчёт расстояния;
  :Уверенность = 1 - (min / total);
fork again
  :Метод нейросетевой;
  :Вектор частот символов;
  :Предсказание модели;
  :Уверенность = softmax[max];
end fork
:Выбор языка с min расстоянием / max вероятностью;
:Вывод результата + статистика;
stop
@enduml