[project]
name = "src"
version = "0.1.0"
description = ""
authors = [
    {name = "lesha",email = "slashertoor@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard] (>=0.119.0,<0.120.0)",
    "ruff (>=0.14.1,<0.15.0)",
    "aiosqlite (>=0.21.0,<0.22.0)",
    "sqlalchemy (>=2.0.44,<3.0.0)",
    "natasha (>=1.6.0,<2.0.0)",
    "python-multipart (>=0.0.20,<0.0.21)",
    "setuptools (>=80.9.0,<81.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.14.1"

[tool.ruff]
line-length=80

[tool.ruff.lint]

# Включение правил для импортов
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort (сортировка импортов)
    "UP", # pyupgrade
    "ARG", # unused arguments
    "COM", # commas
    "ERA", # commented out code
    "FBT", # boolean trap
]


