@startuml sequence
actor user
participant interface
participant api
participant "search system" as sys
participant "rag system" as rag
participant llm
participant algorithm as alg
Database "sql db" as sql
Database "vector db" as vec

user -> interface: search request
interface -> api: search request
api -> rag: answer request
rag -> rag: embed search\nrequest
rag -> vec: get closest chunks
vec --> rag: return chunks
rag -> llm: get answer by chunks and\nsearch request
llm --> rag: return answer and\nconfidence
rag -> rag: check confidence 
alt confidence > 90%
    rag --> api: return answer
    api --> interface: return answer
    interface --> user: return answer
else confidence <= 90%
    rag --> api: return "Not found"
    api --> interface: return None
    interface --> user: return None
end

api -> sys: file list request
sys -> sql: get file ids by words significance from request
sql --> sys: return file ids, significance
sys--> api: return files list
api --> interface: return files
interface --> user: return files by pages
@enduml