@startuml usecase

:Пользователь: as user

user-down->(Отправлять запрос\nна поиск)
user-down->(Получать ответ от\nязыковой модели)
user-down->(Получать файл на\nкотором основан ответ)
(Получать статистику по файлу) .up.> (Получать файл на\nкотором основан ответ): extends
user-down->(Получать статистику по файлу)

@enduml